"""revenue recovery domain tables

Adds the deal/pipeline, follow-up, and leak-detection tables that the Phase-3
revenue-recovery modules depend on: opportunities, proposals, meetings,
sequences, sequence_steps, enrollments, sla_policies, leak_alerts.

The initial migration (8aae99c81fe7) created only the identity + lead +
workflow-engine substrate; the models for these eight tables existed without
backing DDL, so the new opportunity/follow-up/leak endpoints had no schema.

Revision ID: b2f1c7d9e3a4
Revises: 8aae99c81fe7
Create Date: 2026-05-31 14:00:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2f1c7d9e3a4"
down_revision: Union[str, None] = "8aae99c81fe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "NEW",
                "CONTACTED",
                "QUALIFIED",
                "PROPOSAL_SENT",
                "NEGOTIATION",
                "WON",
                "LOST",
                name="opportunitystage",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("value_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("stage_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunities_lead_id"), "opportunities", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_org_id"), "opportunities", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_owner_id"), "opportunities", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_stage"), "opportunities", ["stage"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_team_id"), "opportunities", ["team_id"], unique=False
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SENT",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                name="proposalstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proposals_opportunity_id"), "proposals", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_proposals_org_id"), "proposals", ["org_id"], unique=False)
    op.create_index(op.f("ix_proposals_sent_at"), "proposals", ["sent_at"], unique=False)
    op.create_index(op.f("ix_proposals_status"), "proposals", ["status"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "COMPLETED",
                "NO_SHOW",
                "CANCELLED",
                name="meetingstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meetings_opportunity_id"), "meetings", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_meetings_org_id"), "meetings", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_meetings_scheduled_at"), "meetings", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_meetings_status"), "meetings", ["status"], unique=False)
    op.create_table(
        "sequences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sequences_org_id"), "sequences", ["org_id"], unique=False)
    op.create_table(
        "sequence_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequence_id", sa.Integer(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("delay_hours", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sequence_id"], ["sequences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sequence_id", "step_order", name="uq_step_order"),
    )
    op.create_index(
        op.f("ix_sequence_steps_org_id"), "sequence_steps", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_sequence_steps_sequence_id"),
        "sequence_steps",
        ["sequence_id"],
        unique=False,
    )
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequence_id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "COMPLETED",
                "CANCELLED",
                name="enrollmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sequence_id"], ["sequences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sequence_id", "lead_id", name="uq_enrollment_seq_lead"),
    )
    op.create_index(
        op.f("ix_enrollments_lead_id"), "enrollments", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_org_id"), "enrollments", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_sequence_id"), "enrollments", ["sequence_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_status"), "enrollments", ["status"], unique=False
    )
    op.create_table(
        "sla_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "leak_type",
            sa.Enum(
                "LEAD_IGNORED",
                "OPP_STALLED",
                "MEETING_MISSED",
                "PROPOSAL_COLD",
                name="leaktype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("threshold_hours", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                name="leakseverity",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "leak_type", name="uq_sla_org_leak_type"),
    )
    op.create_index(
        op.f("ix_sla_policies_org_id"), "sla_policies", ["org_id"], unique=False
    )
    op.create_table(
        "leak_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "leak_type",
            sa.Enum(
                "LEAD_IGNORED",
                "OPP_STALLED",
                "MEETING_MISSED",
                "PROPOSAL_COLD",
                name="leaktype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "LEAD",
                "OPPORTUNITY",
                "PROPOSAL",
                "MEETING",
                "ENROLLMENT",
                name="entitytype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                name="leakseverity",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "RESOLVED",
                "DISMISSED",
                name="leakalertstatus",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id",
            "leak_type",
            "entity_type",
            "entity_id",
            "status",
            name="uq_open_alert_per_entity",
        ),
    )
    op.create_index(
        op.f("ix_leak_alerts_org_id"), "leak_alerts", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_leak_alerts_status"), "leak_alerts", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leak_alerts_status"), table_name="leak_alerts")
    op.drop_index(op.f("ix_leak_alerts_org_id"), table_name="leak_alerts")
    op.drop_table("leak_alerts")
    op.drop_index(op.f("ix_sla_policies_org_id"), table_name="sla_policies")
    op.drop_table("sla_policies")
    op.drop_index(op.f("ix_enrollments_status"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_sequence_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_org_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_lead_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_sequence_steps_sequence_id"), table_name="sequence_steps")
    op.drop_index(op.f("ix_sequence_steps_org_id"), table_name="sequence_steps")
    op.drop_table("sequence_steps")
    op.drop_index(op.f("ix_sequences_org_id"), table_name="sequences")
    op.drop_table("sequences")
    op.drop_index(op.f("ix_meetings_status"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_scheduled_at"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_org_id"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_opportunity_id"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_proposals_status"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_sent_at"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_org_id"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_opportunity_id"), table_name="proposals")
    op.drop_table("proposals")
    op.drop_index(op.f("ix_opportunities_team_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_stage"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_owner_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_org_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_lead_id"), table_name="opportunities")
    op.drop_table("opportunities")
    # ### end Alembic commands ###
